version: '3.7'

services:
  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data # Ensure this volume is defined

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      JWT_SECRET: $JWT_SECRET
      REFRESH_SECRET: $REFRESH_SECRET
      REDIS_HOST: redis
      REDIS_PORT: $REDIS_PORT
    volumes:
      - ./src:/app/src # Sync local src folder with container's src folder
      - ./node_modules:/app/node_modules # Avoid re-installing node_modules
    depends_on:
      - postgres
    ports:
      - '3999:3999'
    command: npm run start:dev

volumes:
  pgdata: # Volume for PostgreSQL
  redis-data: # Volume for Redis (add this)
